### PR TITLE
Remove HasProperties and ConfigurationBrowser

### PR DESCRIPTION
**Pull request by rgrinberg**
These interfaces are only used for subclassing and aren't used in any other
project.

### CODE REVIEW

**Comment by rgrinberg** [comment]
@AnthonyMl

**Comment by rgrinberg** [comment]
I think this interface can be moved to protege-server after this anyway

**Comment by bdionne** [comment]
+1 - less code is better

**Review by bdionne — APPROVED** [review]
I approve this PR

**Pull request merged**
